"""selectin for relations in ChatMessage

Revision ID: 5ce855bdadca
Revises: e0e9b93484b7
Create Date: 2025-12-16 00:55:44.089724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ce855bdadca'
down_revision: Union[str, Sequence[str], None] = 'e0e9b93484b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
